docs_dir: docs/source
site_dir: docs/site
site_name: vgrant.docker
site_url: leftxs.github.io/vagrant.docker
repo_url: https://github.com/leftxs/vagrant.docker
site_description: vagrant box, hosting docker for development
pages:
- ['index.md', 'Introduction']
- ['user-guide/configuration.md', 'User Guide', 'Configuring Mashmallow']
- ['user-guide/vim.md', 'User Guide', 'Vim']
- ['about/license.md', 'About', 'License']
- ['about/motivation.md', 'About', 'Motivation']
- ['about/documentation.md', 'About', 'This documentation']
