---
# Install and configure docker

- name: Install needed packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - unzip
    - htop

- name: Install docker
  command: curl -sSL https://get.docker.com/ | sh

- name: Add vagrant user to docker group
  command: gpasswd -a vagrant docker

- name: Add google to docker dns settings
  command: echo 'DOCKER_OPTS="--dns 8.8.8.8"' >> /etc/default/docker


