---
# Install and configure docker

- name: Add docker key
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Add docker to sources.list
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: Update package cache
  apt: update_cache=yes

- name: Install AUFS-kernel support
  command: apt-get install linux-image-extra-$(uname -r) aufs-tools

- name: Install needed packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - htop
    - unzip
    - lxc-docker

- name: Add vagrant user to docker group
  command: gpasswd -a vagrant docker

- name: Add google to docker dns settings
  lineinfile: dest=/etc/default/docker line='DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4"'
  notify: restart docker

