#!/bin/sh

echo
echo " ********************************************************"
echo " * "
echo " * Welcome to your docker development box"
echo " * "
echo " * DNS is set to docker.local"
echo " * " 
echo " ********************************************************"
echo
