---

- name: Doing the last setup steps
  hosts: all
  user: vagrant
  sudo: yes

  roles:
   - upgrade
   - motd
   - bash
   - docker
   - vim

  handlers:
    - name: restart docker
      service: name=docker state=started
